name: Build and Upload Lua Files

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Run the build script
        run: |
          chmod +x ./dist.sh
          ./dist.sh

      - name: Upload Lua files
        uses: actions/upload-artifact@v4
        with:
          name: lua-filters
          path: ./dist/*.lua

